// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrnuMBz_E8D3W2D5_bSzqyuNSx9c3bZ24',
    appId: '1:1056200996320:web:dae05bddaff32f78622785',
    messagingSenderId: '1056200996320',
    projectId: 'storybridgeapp-4993a',
    authDomain: 'storybridgeapp-4993a.firebaseapp.com',
    storageBucket: 'storybridgeapp-4993a.firebasestorage.app',
    measurementId: 'G-N2TZJR2RZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLX_0_Na8_WDLhINW7xWR0vKSwQdstFKc',
    appId: '1:1056200996320:android:175d85e5b7b16a68622785',
    messagingSenderId: '1056200996320',
    projectId: 'storybridgeapp-4993a',
    storageBucket: 'storybridgeapp-4993a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDENXhQZ9tEcUq-LmInOwpyZxAYP9CSqiE',
    appId: '1:1056200996320:ios:522fdfe864e203c1622785',
    messagingSenderId: '1056200996320',
    projectId: 'storybridgeapp-4993a',
    storageBucket: 'storybridgeapp-4993a.firebasestorage.app',
    iosClientId: '1056200996320-99go0g0csl52qk1p3sm6r3ejp2vbf5ml.apps.googleusercontent.com',
    iosBundleId: 'com.example.storybridgeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDENXhQZ9tEcUq-LmInOwpyZxAYP9CSqiE',
    appId: '1:1056200996320:ios:522fdfe864e203c1622785',
    messagingSenderId: '1056200996320',
    projectId: 'storybridgeapp-4993a',
    storageBucket: 'storybridgeapp-4993a.firebasestorage.app',
    iosClientId: '1056200996320-99go0g0csl52qk1p3sm6r3ejp2vbf5ml.apps.googleusercontent.com',
    iosBundleId: 'com.example.storybridgeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrnuMBz_E8D3W2D5_bSzqyuNSx9c3bZ24',
    appId: '1:1056200996320:web:a500da129043d999622785',
    messagingSenderId: '1056200996320',
    projectId: 'storybridgeapp-4993a',
    authDomain: 'storybridgeapp-4993a.firebaseapp.com',
    storageBucket: 'storybridgeapp-4993a.firebasestorage.app',
    measurementId: 'G-QLHF59B1FW',
  );
}
